version: '3.9'
# This file is used to start the database containers
# It is not used in production only for local development and testing
services:
    # Mongo Database service
    mongodb:
      image: mongo:7.0
      command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
      ports:
        - 27017:27017
      # extra_hosts:
      #   - "host.docker.internal:host-gateway"
      healthcheck:
        test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:27017',priority:1000}]}) }" | mongosh --port 27017 --quiet
        interval: 5s
        timeout: 30s
        start_period: 0s
        retries: 30
      volumes:
        - mongodb_data:/data/db
        - mongodb_config:/data/configdb
      # networks:
      #   - my-network
      # environment:
      #   MONGO_INITDB_ROOT_USERNAME: root
      #   MONGO_INITDB_ROOT_PASSWORD: password

volumes:
  mongodb_data:
  mongodb_config:
