name: Build, Test and Deploy to Cloud Run

# This workflow is triggered on push events to the main branch
# To Deploy to Cloud Run, you need to set up the following secrets:
# - GCP_CREDENTIALS: The service account key for the GCP project
# - MONGODB_URI: The MongoDB connection string

# For cloud run to work the following APIs need to be enabled:
# - Cloud Run API
# - Cloud Build API
# - Cloud Storage API
# - Vertex AI API
# - Google Artifact Registry API
# - Google AI Platform Training & Prediction API

# The service account used in the GCP_CREDENTIALS should have the following roles:
# - Cloud Run Developer
# - Cloud Run Source Developer (!very important, if deploying from source)
# - Storage Object Admin
# - Artifact Registry Administrator
# - Service Account User
# - Service Usage Admin
# - Cloud Build Editor
# - Vertex AI User


on:
    push:
        branches:
        - main

env:
    PROJECT_ID: basewiki # Change to your GCP project ID
    SERVICE: basewiki-backend # Change to your desired service name
    REGION: us-central1 # Change to your desired region

jobs:
    ci-cd:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        -   name: Setup Node.js environment
            uses: actions/setup-node@v4
            with:
                node-version: 18
                cache: "npm"
                cache-dependency-path: ./package-lock.json

        -   name: Install Dependencies
            run: npm install

        -   name: Build application
            run: npm run build

        -   name: Copy credentials to .keys folder
            run: mkdir -p .keys && echo $GCP_CREDENTIALS > .keys/gcp-credentials.json
            env:
                GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

        -   name: Start MongoDB
            uses: supercharge/mongodb-github-action@1.11.0
            with:
                mongodb-version: latest
                mongodb-replica-set: rs

        -   name: Test application
            run: npm run test
        
        -   name: Authenticate with Google Cloud
            id: auth
            uses: google-github-actions/auth@v2
            with:
                credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

        -   name: Deploy to Cloud Run
            id: deploy
            uses: 'google-github-actions/deploy-cloudrun@v2'
            with:
                service: ${{ env.SERVICE }}
                # image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}
                region: ${{ env.REGION }}
                project_id: ${{ env.PROJECT_ID }}
                env_vars: |
                    MONGODB_URI=${{ secrets.MONGODB_URI }}
                    GCP_CREDENTIALS=.${{ secrets.GCP_CREDENTIALS }}
                source: ./

        -   name: Output the URL
            run: echo "The URL for the service is ${{ steps.deploy.outputs.url }}"